---
title: "Homework 2- Diagnosing like a Data Doctor"
author: Riyanshi Bohra
format: html
editor: visual
---

# Homework 2-

# Diagnosing like a Data Doctor

# Setting up

```{r}
options(digits = 2)

# Installing and loading required packages
if (!require(pacman))
  install.packages("pacman")

pacman::p_load(dlookr, 
               formattable, 
               here, 
               kableExtra, 
               knitr, 
               missRanger, 
               tidyverse) 
```

## Loading the Tornados dataset

```{r}
#Load the 'tornados.csv' dataset
dataset <- read.csv("/Users/riyanshibohra/Desktop/tornados.csv") 
```

# Diagnosing the data

```{r}
# Display the first few rows of the dataset to get an overview
dataset |>
  head() |>
  formattable()
```

```{r}
# Explore and display the general properties and structure of the dataset
dataset |>
  diagnose() |>
  formattable()
```

# Summary Statistics

## Working with Numerical variables
```{r}
# Compute and display summary statistics for numerical columns in the dataset
dataset |>
  diagnose_numeric() |>
  formattable()
```

## Working with Outliers

```{r}
#Identify and display columns with outliers
diagnose_outlier(dataset) |>
  filter(outliers_ratio > 0) |>
  formattable()
```

```{r}
# Visualize outliers in the dataset
dataset |>
    plot_outlier()
```

## Working with Missing Values(NAs)

```{r}
# Generate a table indicating the presence of missing values in the dataset
dataset |>
  generateNA(p = 0.3) |>
  plot_na_pareto(only_na = TRUE, plot = FALSE) |>
  formattable() 
```

```{r}
# Visualize the intersection of columns with the highest number of missing values

dataset |>
  generateNA(p = 0.3) |>
  select(loss, mag, dy) |>
  plot_na_intersect(only_na = TRUE) 


#The visualization illustrates the intersection of missing values across the columns loss, mag, and dy. The overlaps highlight areas where multiple columns simultaneously lack data.
```

## Working with Categorical variables

```{r}
# Diagnose and display properties of categorical columns in the dataset.

dataset |>
  diagnose_category() |> 
  formattable()
```

# Producing an HTML Summary of the Dataset

```{r}
#Generate a comprehensive web-based report for the dataset. (Note: Currently commented out due to rendering issues.)
#diagnose_web_report(dataset)

#I was unable to render the document without commenting out this chunk of code.#
```
